name: scp files
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v0.1.4
    - name: copy file via ssh password
      uses: appleboy/scp-action@v0.1.4
      with:
        host: "80.90.187.31"
        username: root
        password: cDTSs4nc
        port: 22
        source: "."
        target: "/servers_folder/bfg-bot/"
